I'm gettin' better at sneaking up on you like this.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -20,6 +20,48 @@ notifications:
   slack:
     on_failure: always
 
+fleet_script_minikube_vault_consul_tasks : &fleet_script_minikube_vault_consul_tasks
+      script:
+          - |
+            set -eo pipefail #safety for script
+            if [[ $(egrep -c '(vmx|svm)' /proc/cpuinfo) == 0 ]]; then #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
+                     echo "virtualization is not supported"
+            else
+                  echo "===================================="
+                  echo eval "$(egrep -c '(vmx|svm)' /proc/cpuinfo)" 2>/dev/null
+                  echo "===================================="
+                  echo "virtualization is supported"
+            fi
+          - sudo apt-get -qq -y install conntrack #X Sorry, Kubernetes v1.18.3 requires conntrack to be installed in root's path
+          - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/ # Download kubectl
+          - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/ # Download minikube
+          - mkdir -p $HOME/.kube $HOME/.minikube
+          - touch $KUBECONFIG
+          - sudo minikube start --profile=minikube --vm-driver=none --kubernetes-version=v$KUBERNETES_VERSION #the none driver, the kubectl config and credentials generated are owned by root in the root user’s home directory
+          - minikube update-context --profile=minikube
+          - "sudo chown -R travis: /home/travis/.minikube/"
+          - eval "$(minikube docker-env --profile=minikube)" && export DOCKER_CLI='docker'
+          - echo "=========================================================================================="
+          - kubectl version --client #ensure the version
+          - kubectl cluster-info
+          - minikube status
+          - echo "=========================================================================================="
+          - |
+            echo "Waiting for Kubernetes to be ready ..."
+            for i in {1..150}; do # Timeout after 5 minutes, 150x2=300 secs
+              if kubectl get pods --namespace=kube-system -lcomponent=kube-addon-manager|grep Running && \
+                 kubectl get pods --namespace=kube-system -lk8s-app=kube-dns|grep Running ; then
+                break
+              fi
+              sleep 2
+            done
+          - echo "============================status check=============================================================="
+          - minikube status
+          - kubectl cluster-info
+          - kubectl get pods --all-namespaces;
+          - kubectl get pods -n default;
+          - minikube dashboard
+
 
 fleet_script_minikube_latest_tasks : &fleet_script_minikube_latest_tasks
       script:
@@ -139,6 +181,33 @@ matrix:
   fast_finish: true
   include:
 
+    - name: "minikube consul vault latest  Python 3.7 on bionic" #OK
+      dist: bionic
+      language: python
+      python: 3.7
+      before_install:
+        - pip3 install virtualenv
+        - virtualenv -p $(which python3) ~venvpy3
+        - source ~venvpy3/bin/activate
+      <<: *fleet_install_tasks
+      <<: *fleet_script_tasks
+      <<: *fleet_script_minikube_vault_consul_tasks
+      after_success:
+        - deactivate
+
+    - name: "minikube consul  Python 3.7 on xenial" #OK
+      dist: bionic
+      language: python
+      python: 3.7
+      before_install:
+        - pip3 install virtualenv
+        - virtualenv -p $(which python3) ~venvpy3
+        - source ~venvpy3/bin/activate
+      <<: *fleet_install_tasks
+      <<: *fleet_script_tasks
+      <<: *fleet_script_minikube_latest_tasks
+      after_success:
+        - deactivate
 
     # - name: "minikube 1.18.1 Python 3.7 on bionic"
     #   dist: bionic
@@ -168,33 +237,6 @@ matrix:
     #   after_success:
     #     - deactivate
 
-    - name: "minikube latest  Python 3.7 on bionic" #OK
-      dist: bionic
-      language: python
-      python: 3.7
-      before_install:
-        - pip3 install virtualenv
-        - virtualenv -p $(which python3) ~venvpy3
-        - source ~venvpy3/bin/activate
-      <<: *fleet_install_tasks
-      <<: *fleet_script_tasks
-      <<: *fleet_script_minikube_latest_tasks
-      after_success:
-        - deactivate
-
-    - name: "minikube latest  Python 3.7 on xenial" #OK
-      dist: xenial
-      language: python
-      python: 3.7
-      before_install:
-        - pip3 install virtualenv
-        - virtualenv -p $(which python3) ~venvpy3
-        - source ~venvpy3/bin/activate
-      <<: *fleet_install_tasks
-      <<: *fleet_script_tasks
-      <<: *fleet_script_minikube_latest_tasks
-      after_success:
-        - deactivate
 
     # - name: "Python 3.7 on bionic arm64" # package architecture (amd64) does not match system (arm64)
     #   os: linux
