We thought about it for a long time, "Endeavor to persevere."

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -20,13 +20,24 @@ notifications:
 fleet_script_minikube_latest_tasks : &fleet_script_minikube_latest_tasks
       script:
           # - egrep -c '(vmx|svm)' /proc/cpuinfo   #check if virtualization is supported on Linux, xenial fails, bionic works
+          # - |
+          #   if [[ $(lsb_release -rs) == "18.04" ]]; then #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
+          #            egrep -c '(vmx|svm)' /proc/cpuinfo
+          #            echo "virtualization is supported"
+          #     else
+          #            echo "virtualization is not supported"
+          #     fi
           - |
-            if [[ $(lsb_release -rs) == "18.04" ]]; then #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
-                     egrep -c '(vmx|svm)' /proc/cpuinfo
-                     echo "virtualization is supported"
-              else
+            set -eux #safety for script
+            if [ $(egrep -c '(vmx|svm)' /proc/cpuinfo) == 0 ]#check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
+            then
                      echo "virtualization is not supported"
-              fi
+            else
+                  echo "===================================="
+                  echo $(egrep -c '(vmx|svm)' /proc/cpuinfo)
+                  echo "===================================="
+                  echo "virtualization is not supported"
+            fi          
           - sudo apt-get -qq -y install conntrack #http://conntrack-tools.netfilter.org/
           - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/ # Download kubectl
           - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/ # Download minikube
@@ -66,12 +77,16 @@ fleet_script_minikube_tasks : &fleet_script_minikube_tasks
           # overriding global env variables
           # - egrep -c '(vmx|svm)' /proc/cpuinfo   #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
           - |
-            if [[ $(lsb_release -rs) == "18.04" ]]; then #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
-                     egrep -c '(vmx|svm)' /proc/cpuinfo
-                     echo "virtualization is supported"
-              else
+            set -eux #safety for script
+            if [ $(egrep -c '(vmx|svm)' /proc/cpuinfo) == 0 ]#check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
+            then
                      echo "virtualization is not supported"
-              fi
+            else
+                  echo "===================================="
+                  echo $(egrep -c '(vmx|svm)' /proc/cpuinfo)
+                  echo "===================================="
+                  echo "virtualization is not supported"
+            fi
           - export MINIKUBE_WANTUPDATENOTIFICATION=false
           - export MINIKUBE_WANTREPORTERRORPROMPT=false
           - export CHANGE_MINIKUBE_NONE_USER=true
@@ -161,7 +176,7 @@ matrix:
       after_success:
         - deactivate
 
-    - name: "minikube latest  Python 3.7 on bionic"
+    - name: "minikube latest  Python 3.7 on bionic" #OK
       dist: bionic
       language: python
       python: 3.7
