They have him pulling a wagon up in Kansas, I bet.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -77,13 +77,12 @@ fleet_script_minikube_tasks : &fleet_script_minikube_tasks
           # overriding global env variables
           # - egrep -c '(vmx|svm)' /proc/cpuinfo   #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
           - |
-            set -euo pipefail #safety for script
-            if [ $(egrep -c '(vmx|svm)' /proc/cpuinfo) == 0 ]#check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
-            then
+            set -euox pipefail #safety for script
+            if [[ $(egrep -c '(vmx|svm)' /proc/cpuinfo) == 0 ]]; then #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
                      echo "virtualization is not supported"
             else
                   echo "===================================="
-                  echo $(egrep -c '(vmx|svm)' /proc/cpuinfo)
+                  echo eval "$(egrep -c '(vmx|svm)' /proc/cpuinfo)" 2>/dev/null
                   echo "===================================="
                   echo "virtualization is not supported"
             fi
