They say most of your brain shuts down in cryo-sleep.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -16,6 +16,62 @@ env:
 notifications:
   slack:
     on_failure: always
+fleet_script_minikube_latest_app_tasks : &fleet_script_minikube_latest_app_tasks
+      script:
+          # - set -eox pipefail #safety for script
+          - |
+            if [[ $(egrep -c '(vmx|svm)' /proc/cpuinfo) == 0 ]]; then #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
+                     echo "virtualization is not supported"
+            else
+                  echo "===================================="
+                  echo eval "$(egrep -c '(vmx|svm)' /proc/cpuinfo)" 2>/dev/null
+                  echo "===================================="
+                  echo "virtualization is supported"
+            fi
+          - sudo apt-get -qq -y install conntrack #http://conntrack-tools.netfilter.org/
+          - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/ # Download kubectl
+          - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/ # Download minikube
+          - mkdir -p $HOME/.kube $HOME/.minikube
+          - touch $KUBECONFIG
+          - sudo minikube start --profile=minikube --vm-driver=none --kubernetes-version=v$KUBERNETES_VERSION #the none driver, the kubectl config and credentials generated are owned by root in the root user’s home directory
+          - minikube update-context --profile=minikube
+          - "sudo chown -R travis: /home/travis/.minikube/"
+          - eval "$(minikube docker-env --profile=minikube)" && export DOCKER_CLI='docker'
+          - echo "=========================================================================================="
+          - kubectl version --client #ensure the version
+          - kubectl cluster-info
+          - minikube status
+          - echo "=========================================================================================="
+          - |
+            echo "Waiting for Kubernetes to be ready ..."
+            for i in {1..150}; do # Timeout after 5 minutes, 150x2=300 secs
+              if kubectl get pods --namespace=kube-system -lk8s-app=kube-dns|grep Running ; then
+                break
+              fi
+              sleep 2
+            done
+          # - |
+          #   echo "Waiting for Kubernetes to be ready ..."
+          #   for i in {1..150}; do # Timeout after 5 minutes, 150x2=300 secs
+          #     if kubectl get pods --namespace=kube-system -lcomponent=kube-addon-manager|grep Running && \
+          #        kubectl get pods --namespace=kube-system -lk8s-app=kube-dns|grep Running ; then
+          #       break
+          #     fi
+          #     sleep 2
+          #   done
+          - echo "============================status check=============================================================="
+          - minikube status
+          - kubectl cluster-info
+          - kubectl get pods --all-namespaces;
+          - kubectl get pods -n default;
+          - echo "=============================Inspection============================================================="
+          - kubectl get pod -o wide #The IP column will contain the internal cluster IP address for each pod.
+          - kubectl get service --all-namespaces # find a Service IP,list all services in all namespaces
+          - sudo kubectl apply -f https://openebs.github.io/charts/openebs-operator.yaml #install OpenEBS
+          - kubectl get service --all-namespaces # find a Service IP,list all services in all namespaces-
+          - kubectl get pods -n openebs -l openebs.io/component-name=openebs-localpv-provisioner #Observe localhost provisioner pod
+          - kubectl get sc #Check the storage Class
+          - Create a PVC
 
 fleet_script_minikube_latest_tasks : &fleet_script_minikube_latest_tasks
       script:
@@ -136,6 +192,7 @@ fleet_script_minikube_latest_tasks : &fleet_script_minikube_latest_tasks
           - kubectl get pods --all-namespaces;
           # - docker inspect --format '{{ .State.Pid }}' container-id-or-name #get the process ID of either container, take note of the container ID or name
           - echo "=========================================================================================="
+
 fleet_script_minikube_tasks : &fleet_script_minikube_tasks
       script:
           # overriding global env variables
@@ -245,7 +302,8 @@ matrix:
         - source ~venvpy3/bin/activate
       <<: *fleet_install_tasks
       <<: *fleet_script_tasks
-      <<: *fleet_script_minikube_latest_tasks
+      # <<: *fleet_script_minikube_latest_tasks
+      <<: *fleet_script_minikube_latest_app_tasks
       after_success:
         - deactivate
 
