не мочь

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -514,73 +514,73 @@ fleet_script_minikube_latest_tasks : &fleet_script_minikube_latest_tasks
           # - ipvsadm -Ln -t IPADDRESS:PORT #show a single Service IP
           - echo "=========================================================================================="
 
-fleet_script_minikube_tasks : &fleet_script_minikube_tasks
-      script:
-          # overriding global env variables
-          - |
-            set -eo pipefail #safety for script
-            if [[ $(egrep -c '(vmx|svm)' /proc/cpuinfo) == 0 ]]; then #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
-                     echo "virtualization is not supported"
-            else
-                  echo "===================================="
-                  echo eval "$(egrep -c '(vmx|svm)' /proc/cpuinfo)" 2>/dev/null
-                  echo "===================================="
-                  echo "virtualization is supported"
-            fi
-          - export MINIKUBE_WANTUPDATENOTIFICATION=false
-          - export MINIKUBE_WANTREPORTERRORPROMPT=false
-          - export CHANGE_MINIKUBE_NONE_USER=true
-          - export KUBECTL_VERSION=1.18.3
-          - export KUBERNETES_VERSION=1.18.3
-          - export MINIKUBE_VERSION=1.18.3
-          - sudo apt-get -qq -y install conntrack #X Sorry, Kubernetes v1.18.3 requires conntrack to be installed in root's path
-          - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v$KUBECTL_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/ # Download kubectl
-          - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v$MINIKUBE_VERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/ # Download minikube
-          - mkdir -p $HOME/.kube $HOME/.minikube
-          - touch $KUBECONFIG
-          - sudo minikube start --profile=minikube --vm-driver=none --kubernetes-version=v$KUBERNETES_VERSION #--vm-driver=none, doesn't use a VM, but containers the none driver, the kubectl config and credentials generated are owned by root in the root user’s home directory
-          - minikube update-context --profile=minikube
-          - "sudo chown -R travis: /home/travis/.minikube/"
-          - eval "$(minikube docker-env --profile=minikube)" && export DOCKER_CLI='docker'
-          - echo "=========================================================================================="
-          - kubectl version --client #ensure the version
-          - kubectl cluster-info
-          - minikube status
-          - echo "=========================================================================================="
-          - |
-            echo "Waiting for Kubernetes to be ready ..."
-            for i in {1..150}; do # Timeout after 5 minutes, 150x2=300 secs
-              if kubectl get pods --namespace=kube-system -lcomponent=kube-addon-manager|grep Running && \
-                 kubectl get pods --namespace=kube-system -lk8s-app=kube-dns|grep Running ; then
-                break
-              fi
-              sleep 2
-            done
-          - |
-            JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
-            until kubectl -n kube-system get pods -lk8s-app=kube-dns -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
-              sleep 1;
-              echo "waiting for kube-dns to be available";
-              kubectl get pods --all-namespaces;
-            done
-          - kubectl run travis-example --image=redis --labels="app=travis-example" # Create example Redis deployment on Kubernetes.
-          - | # Make sure created pod is scheduled and running.
-            JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
-            until kubectl -n default get pods -lapp=travis-example -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
-              sleep 1;
-              echo "waiting for travis-example deployment to be available";
-              kubectl get pods -n default;
-            done
-          - echo "============================================="
-          - kubectl get pods --all-namespaces;
-          - kubectl get pods -n default;
-          - echo "============================================="
-fleet_script_tasks : &fleet_script_tasks
-      script:
-        - python --version
-fleet_install_tasks : &fleet_install_tasks
-      install:
-        - pip install -r requirements.txt
+# fleet_script_minikube_tasks : &fleet_script_minikube_tasks
+#       script:
+#           # overriding global env variables
+#           - |
+#             set -eo pipefail #safety for script
+#             if [[ $(egrep -c '(vmx|svm)' /proc/cpuinfo) == 0 ]]; then #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
+#                      echo "virtualization is not supported"
+#             else
+#                   echo "===================================="
+#                   echo eval "$(egrep -c '(vmx|svm)' /proc/cpuinfo)" 2>/dev/null
+#                   echo "===================================="
+#                   echo "virtualization is supported"
+#             fi
+#           - export MINIKUBE_WANTUPDATENOTIFICATION=false
+#           - export MINIKUBE_WANTREPORTERRORPROMPT=false
+#           - export CHANGE_MINIKUBE_NONE_USER=true
+#           - export KUBECTL_VERSION=1.18.3
+#           - export KUBERNETES_VERSION=1.18.3
+#           - export MINIKUBE_VERSION=1.18.3
+#           - sudo apt-get -qq -y install conntrack #X Sorry, Kubernetes v1.18.3 requires conntrack to be installed in root's path
+#           - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v$KUBECTL_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/ # Download kubectl
+#           - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v$MINIKUBE_VERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/ # Download minikube
+#           - mkdir -p $HOME/.kube $HOME/.minikube
+#           - touch $KUBECONFIG
+#           - sudo minikube start --profile=minikube --vm-driver=none --kubernetes-version=v$KUBERNETES_VERSION #--vm-driver=none, doesn't use a VM, but containers the none driver, the kubectl config and credentials generated are owned by root in the root user’s home directory
+#           - minikube update-context --profile=minikube
+#           - "sudo chown -R travis: /home/travis/.minikube/"
+#           - eval "$(minikube docker-env --profile=minikube)" && export DOCKER_CLI='docker'
+#           - echo "=========================================================================================="
+#           - kubectl version --client #ensure the version
+#           - kubectl cluster-info
+#           - minikube status
+#           - echo "=========================================================================================="
+#           - |
+#             echo "Waiting for Kubernetes to be ready ..."
+#             for i in {1..150}; do # Timeout after 5 minutes, 150x2=300 secs
+#               if kubectl get pods --namespace=kube-system -lcomponent=kube-addon-manager|grep Running && \
+#                  kubectl get pods --namespace=kube-system -lk8s-app=kube-dns|grep Running ; then
+#                 break
+#               fi
+#               sleep 2
+#             done
+#           - |
+#             JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
+#             until kubectl -n kube-system get pods -lk8s-app=kube-dns -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
+#               sleep 1;
+#               echo "waiting for kube-dns to be available";
+#               kubectl get pods --all-namespaces;
+#             done
+#           - kubectl run travis-example --image=redis --labels="app=travis-example" # Create example Redis deployment on Kubernetes.
+#           - | # Make sure created pod is scheduled and running.
+#             JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
+#             until kubectl -n default get pods -lapp=travis-example -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
+#               sleep 1;
+#               echo "waiting for travis-example deployment to be available";
+#               kubectl get pods -n default;
+#             done
+#           - echo "============================================="
+#           - kubectl get pods --all-namespaces;
+#           - kubectl get pods -n default;
+#           - echo "============================================="
+# fleet_script_tasks : &fleet_script_tasks
+#       script:
+#         - python --version
+# fleet_install_tasks : &fleet_install_tasks
+#       install:
+#         - pip install -r requirements.txt
 
 
 matrix:
@@ -590,7 +590,6 @@ matrix:
     - name: "minikube wo snaps Python 3.7 on bionic amd64"
       dist: bionic
       arch: amd64
-      addons:
       language: python
       python: 3.7
       before_install:
@@ -607,7 +606,6 @@ matrix:
     - name: "openebs minikube wo snaps Python 3.7 on bionic amd64"
       dist: bionic
       arch: amd64
-      addons:
       language: python
       python: 3.7
       before_install:
@@ -624,7 +622,6 @@ matrix:
     - name: "k8s dashboard minikube wo snaps Python 3.7 on bionic amd64"
       dist: bionic
       arch: amd64
-      addons:
       language: python
       python: 3.7
       before_install:
